module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'subject-case': [2, 'always', 'sentence-case'],
    'type-enum': [
			2,
			'always',
			[
				'build',
        '📦 build',
				'chore',
        '🚚 chore',
				'ci',
        '🧱 ci',
				'docs',
				'💡 docs',
				'feat',
        '✨ feat',
				'fix',
        '💥 fix',
				'perf',
				'⚡ perf',
				'refactor',
				'♻️ refactor',
				'revert',
				'💥 revert',
				'style',
				'👌 style',
				'test',
        '🧪 test',
			],
		],
  },
};