version: '3.8'

services:
  db_service:
    image: mysql:8.0.21
    container_name: container-db
    platform: linux/x86_64
    ports:
      - 3072:3306 #LOCAL_PORT:CONTAINER_PORT
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_DATABASE=db
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
volumes:
  db_data:
